# Generated by Django 3.1.2 on 2020-10-19 07:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201014_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(elp_text='Tekst do wyświetlenia', required=True))]))], blank=True, null=True),
        ),
    ]
